/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ga4gh.starterkit.passport.broker;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.ga4gh.starterkit.passport.broker.config.ServiceInfoConfig;

@SpringBootApplication
@EnableConfigurationProperties(ServiceInfoConfig.class)
public class PassportBroker {
    
    public static void main(String[] args) {
        System.out.println("HELLO WOOOORDDLLLL");
        SpringApplication.run(PassportBroker.class, args);
    }
}
